
spring.datasource.url=jdbc:mysql://b9xrlwssp0npfjzjfg2g-mysql.services.clever-cloud.com:3306/b9xrlwssp0npfjzjfg2g?serverTimezone=UTC
spring.datasource.username=uayvh9glwwt7y21y
spring.datasource.password=dRirRxPrdwwVK7n6S8W8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect